name: ui
description: The UI package.
publish_to: 'none'
version: 1.0.0

environment:
   sdk: ^3.2.0

dependencies:
  equatable: ^2.0.5
  extended_image: ^8.2.0
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  image_picker: ^1.0.5
  localization:
    path: ../localization

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  pro_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/placeholders/
    - assets/colors/

flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml
  output: lib/generated/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
