targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
      freezed:
        options:
          map: false
          when: 
            when: false
            maybe_when: false
            when_or_null: false