name: models
description: The models package.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.2.0

dependencies:
  fast_immutable_collections: ^9.2.0
  freezed_annotation: ^2.4.1
  intl: ^0.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  pro_lints: ^2.0.2
